FROM ducksouplab/debian-gstreamer:deb11-cuda12.4-gst1.22.10

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get update && apt-get install -y build-essential cmake pkg-config git meson
        # libopenblas-dev liblapack-dev  # dlib dependencies

# build dependencies
RUN apt-get update && apt-get install -y libsm-dev libxext-dev

# dlib default model
RUN apt-get update && apt-get install -y libdlib-data

WORKDIR /gstmozza